### ISSUE TITLE
project fixing

### ISSUE THREAD

**Issue by mstankovic** [code-incubus/SeleniumKapua#2]
dodaj drivers folder u .gitignore
visak u pomu ti je ovaj dependecncy -> webdriverextensions (imas ga u plugin sekciji to je dovoljno)
zakomplikovao si https://github.com/code-incubus/SeleniumKapua/blob/master/src/test/java/commons/utils/DriverProperties.java klasu:
-> 
- ponavlja ti se mnogo koda - samo system.setProperty treba da ti bude u petlji, sve ostalo izvan, tako da ti posle toga uopste i ne treba henlovanje kroz petlju da zatvaras browser

msm ok je i ovo ali bolje je da bude kod citljiviji.. sve ostalo ok.
Ne znam sto ti puca rugi test, aj sutra cuda checkputujem pa da probam u lokalu

**Comment by code-incubus** [comment]
Hej @mstankovic dodao sam jedan commit u kom sam obrisao "po meni" visak klasu. Ti vidi da li je ok ostalo.
